<a href="https://colab.research.google.com/github/Nishchal-ll/Machine-Learning/blob/main/Introduction%20to_Machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Introduction to NumPy*

What we will cover?


*   Creating single dimensional arrays 👌👍
*   Multidimensional arrays
*   Randomly generated arrays
*   Randomly generated arrays
*   Element wise operations
*   Summarizing operations








# Single Dimensional Arrays

In [8]:
import numpy as np
#create an array with all the elements to be zeros


np.zeros(5)


array([0., 0., 0., 0., 0.])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
#create array of size 11 with all elements 3
np.full(11, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [12]:
np.array([1,2,3,4,5])
# self array

array([1, 2, 3, 4, 5])

In [15]:
np.arange(3, 10)
# starting with 3 and going till 9 excluding 10

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
#create an array with evenly spaced numbers with specified range
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

#Multi Dimensional Array

In [26]:
np.zeros((3,4))
# 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((2,2))
#square matrix with all elements 1

array([[1., 1.],
       [1., 1.]])

In [37]:
# square 3 by 3 matrix with elements staring from 1 to 9  big bracket used

np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
# changing 2 to 20 by initializing array to varibale and changing index
array= np.array([[1,2,3],[4,5,6],[7,8,9]])
array[0, 1]=20
print(array)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [44]:
# changing third row to 1,1,1
array= np.array([
    [1,2,3],
 [4,5,6],
  [7,8,9]
    ])
array[2]=[1,1,1]
print(array)

[[1 2 3]
 [4 5 6]
 [1 1 1]]


In [45]:
# changing third column to 1,1,2
array= np.array([
    [1,2,3],
 [4,5,6],
  [7,8,9]
    ])
array[:, 2]=2
print(array)

[[1 2 2]
 [4 5 2]
 [7 8 2]]


In [47]:
# creating 3*3 dimensional array with all elements 10
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Randomly generated arrays


- Numpy can create arrays filled with random numbers
- to ensure the reproductibility, you can set a seed using ``` np.random.seed()``` It will generate the exact same random numbers for each executions
-If you remove or change the seed values, the sequence of random numbers will be changed


In [50]:
np.random.rand(5)


array([0.97439155, 0.75819898, 0.79814318, 0.90653071, 0.22896115])

In [53]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [54]:
np.random.randn(5,2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [63]:
np.random.randint( low=0, high=100, size=(6,9))

array([[ 4, 48, 59, 96, 47, 58, 58, 75, 77],
       [73,  8, 48, 68, 43, 53, 81, 48, 93],
       [70, 93, 45,  4, 60, 74, 36, 44, 65],
       [95, 81, 94, 28, 43, 35, 71, 83, 97],
       [39, 50, 55,  2, 39, 80, 30, 76, 28],
       [58, 83, 41,  5, 41, 57, 30, 47, 89]])